version: "3.9"
services:
  postgres:
    container_name: playground-postgres
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=playground-db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
  flyway:
    container_name: playground-db-flyway
    environment:
      - FLYWAY_USER=default
      - FLYWAY_PASSWORD=default
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/playground-db
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql migrate
    volumes:
      - ${PWD}/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
